#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
#set -x #print commands

git log -1
git status -uno

if [[ "${1-}" == "-n" ]]; then
  # Dry run
  exit
fi

git add -u .
git commit --amend --no-edit
git push --force-with-lease
