#!/bin/bash
#set -x #print commands
#set -e #exit on failed command
set -u #fail on undefined variable
echo `date` Build started >> ~/.buildlog

cd ~/ouifennec && ./build.sh $@
if [ $? -eq 0 ];then
 date
 echo `date` Build finished >> ~/.buildlog
 true
else 
 notify-send "Build failed"
 echo `date` Build failed >> ~/.buildlog
 false
fi
