#!/bin/bash
set -x #print commands
set -e #exit on failed command
set -u #fail on undefined variable

cd ~/ouifennec && ./build.sh $@
ls -al gecko-dev/obj-arm-linux-androideabi/dist/ceno-64.0.1.en-US.android-arm.apk
date
