#!/bin/bash
set -x #print commands
set -e #exit on failed command
set -u #fail on undefined variable

open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security
