#!/bin/bash
#set -x #print commands
#set -e #exit on failed command
set -u #fail on undefined variable

NAME=$1; shift
if [ $# -eq 0 ];then 
 DIRS="."
else 
 DIRS=$@
fi
for DIR in $DIRS; do
 find $DIR -type d -name $NAME
done
