#!/usr/bin/env python3
# -*- mode: python;
import sys, getopt
from data.geojson import *
from data.log import *


optlist, args = getopt.getopt(sys.argv[1:], 'n:')
count = 10
if '-n' in optlist:
  count = optlist['-n']

if len(args) != 1:
  fail("Usage: %s [-n COUNT] FILE" % (sys.argv[0]))

geojson = read_geojson(args[0])
for i in range(count):
  print(geojson[i])


