#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
#set -x #print commands

ps -u $(id -u) -o pid= \
    | xargs -I PID -r cat /proc/PID/environ 2> /dev/null \
    | tr '\0' '\n' \
    | grep ^DISPLAY=: \
    | sort -u
