#!/bin/bash
set -x #print commands
set -e #exit on failed command

#gcloud compute instances list|grep ^$1|awk '{print $5}'
#set -u #fail on undefined variable
#NAME=${1:-deb}
#gcloud compute instances list|grep ^$NAME|awk '{print $9}'
echo deb.sjf.io
