#!/usr/bin/env bash

set -eu

FILES="${@:-.}"

modified_files=$(git diff --name-only $FILES)
if [ -n "$modified_files" ]; then
  echo Modified files:
  echo "$modified_files"
  echo
fi
new_files=$(git ls-files --others --exclude-standard $FILES)
if [ -n "$new_files" ]; then
  echo New files:
  echo "$new_files"
  #git-check-new-files-stashed.sh $FILES || true
fi

if [[ -z "$modified_files" && -z "$new_files" ]];then
  echo No changes
  exit 0
fi

read -p "Continue? (y/N): " -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
  if [ -n "$modified_files" ]; then
    echo git restore $FILES
    git restore $FILES
  fi
  if [ -n "$new_files" ]; then
    echo git clean -fd $FILES
    git clean -fd $FILES
  fi
else
  echo "Cancelled"
fi
