#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
#set -x #print commands

CURRENT_BRANCH=$(git branch --show-current)

HAS_LOCAL_CHANGES=
if git diff-index --quiet HEAD --; then
  : # There are no local changes to indexed files.
else
  HAS_LOCAL_CHANGES=1
fi

function branch_exists() {
  name=$1
  git show-ref --verify --quiet refs/heads/"$name"
}

function remote_branch_exists() {
  echo Checking remote branches...
  git ls-remote --exit-code --heads origin "$branch_to_delete" >/dev/null 2>&1
}

function co() {
  name=$1
  # Check if branch exists locally
  if git show-ref --verify --quiet refs/heads/"$name"; then
      git checkout "$name"
      return
  fi
  # Check if branch exists on remote
  if git ls-remote --heads origin "$name" | grep -q "$name"; then
      git checkout -b "$name" origin/"$name"
      return
  fi
  # Create a new branch
  git checkout -b "$name"
}


function stash_before() {
  NAME=${1:-}
  if [[ -n $HAS_LOCAL_CHANGES ]]; then
    git stash -q -m "$NAME" --include-untracked
  fi
}

function pop_after() {
  if [[ -n $HAS_LOCAL_CHANGES ]]; then
    git stash pop -q
  fi
}


function createPrUrl() {
  repo_url=$(git remote get-url origin | sed 's/\.git$//' | sed 's/git@github.com:/https:\/\/github.com\//')
  echo "$repo_url/compare/$CURRENT_BRANCH"
}
