#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
# set -x #print commands

. ~/scripts/git-utils

function createPrUrl() {
  repo_url=$(git remote get-url origin | sed 's/\.git$//' | sed 's/git@github.com:/https:\/\/github.com\//')
  echo "$repo_url/compare/$CURRENT_BRANCH"
}

stash_before getfetch-tmp

git fetch origin
git rebase origin/main
npm run install:all

pop_after

git push --force-with-lease

if [[ $CURRENT_BRANCH != "main" ]]; then
  gh pr view --json url --jq '.url' 2>/dev/null || createPrUrl
fi
