#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
# set -x #print commands

. ~/scripts/git-utils

UPDATED=no

# just drop changes to this file because it is useless and always getting auto-updated
[[ -f package-lock.json ]] && git restore package-lock.json

stash_before gitfetch-tmp


echo 'git fetch origin && git rebase origin/main'
if set +u git fetch origin && git rebase origin/main; then

  # was HEAD updated?
  if [[ "$(git rev-parse HEAD)" != "$(git rev-parse HEAD@{1})" ]]; then
    UPDATED=yes
  fi
else
  rich "[bold red]Failed to fetch and rebase[/bold red]" --print
fi

# Reset -u
set -u

pop_after || (rich "[bold red]FAILED TO POP STASH![/bold red]" --print && exit 1)


if [[ $UPDATED == yes ]]; then

  git log --oneline HEAD@{1}..HEAD

  [[ -f package.json ]] && npm run install:all

  # Update remote branch
  git push --force-with-lease

  if [[ $CURRENT_BRANCH != "main" ]]; then
    gh pr view --json url --jq '.url' 2>/dev/null || createPrUrl
  fi
else
  rich "[yellow]No changes fetched" --print
fi
