#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
set -x #print commands

. ~/scripts/git-utils

BRANCH=${1:-$(cat /dev/random | tr -dc 'a-z' | head -c 4)}

NAME=$(get_name $BRANCH)

set -x
git checkout $MAIN
git fetch
git pull
git checkout -b $NAME
