#!/bin/bash
set -x #print commands
set -e #exit on failed command
set -u #fail on undefined variable

adb install -r -d ~/ouifennec/gecko-dev/obj-arm-linux-androideabi/dist/ceno-64.0.1.en-US.android-arm.apk
if [ $? -eq 0 ];then
 notify-send "adb install" "APK installed"
else
 notify-send "adb install" "APK install failed"
fi
