#!/bin/bash
set -u
set -x
set -e
name=~/scripts/$1
if [ ! -f $name ]; then
  cat << EOF > $name
#!/bin/bash
set -x #print commands
set -e #exit on failed command
set -u #fail on undefined variable

EOF
fi
chmod a+x $name
is_mac && exec subl $name

vim "+normal G$" +startinsert $name


