#!/bin/bash
set -u
set -x
set -e
name=~/scripts/$1
if [ ! -f $name ]; then
  cat << EOF > $name
#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
set -x #print commands


EOF
fi
chmod a+x $name
subl $name
