#!/bin/bash
set -u
set -x
set -e
name=~/scripts/$1
if [ ! -f $name ]; then
  cat << EOF > $name
#!/bin/bash
set -e #exit on failed command
set -u #fail on undefined variable
set -x #print commands

EOF
else
  echo "File already exists: $name" >&2 || true
fi
chmod a+x $name

if [[ `is_mac` ]]; then
  exec sublime $name
else
  sopen $name
  #vim "+normal G$" +startinsert $name
fi


