#!/bin/bash
set -ue

# sshtunnel.sh &
# sublime_server.py &

mounts=(
    # "box:/home/sjf/scripts     $HOME/scripts1"
    # "box:/home/sjf/sjf         $HOME/sjf1"
    # "box:/home/sjf/librameta   $HOME/box2"
    # "box:/home/sjf/sbb         $HOME/sbb"
    # "beekey.buzz:/home/sjf/sbb $HOME/sbb.local"
    "box:/home/sjf/discord     $HOME/discord"
)

for entry in "${mounts[@]}"; do
    read -r src dest <<< "$entry"
    dir=$(basename $dest)
    if [[ ! -d "$dest" ]]; then
      mkdir "$dest"
    fi
    umount "$dest" 2>/dev/null || true
    sshfs "$src" "$dest" -o "volname=$dir,ServerAliveInterval=15,reconnect,follow_symlinks,defer_permissions,noappledouble,Compression=no,kill_on_unmount" && echo Mounted $src
done
