#!/bin/bash
set -x #print commands
set -e #exit on failed command
set -u #fail on undefined variable

NUM=$(echo $1 | sed 's/[^0-9]*//g')
savesol $1
cp leetcode/Driver.java leetcode/q${NUM}Driver.java

