#!/usr/bin/env python
import http.server
import ssl
import sys

PORT = 8080
if len(sys.argv) > 1:
  PORT = int(sys.argv[1])

def get_ssl_context(certfile, keyfile):
  context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
  context.load_cert_chain(certfile, keyfile)
  context.set_ciphers("@SECLEVEL=1:ALL")
  return context

context = get_ssl_context("cert.pem", "key.pem")

address = ('0.0.0.0', PORT)
print(f"Listening on {address}")
httpd = http.server.HTTPServer(address, http.server.SimpleHTTPRequestHandler)
httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
httpd.serve_forever()
