#!/usr/bin/env python

import os, sys
import http.server
import socketserver

if len(sys.argv) > 1:
  port = int(sys.argv[1])
else:
  port = int(os.environ.get('PORT', '8081'))

if len(sys.argv) > 2:
  host = sys.argv[2]
else:
  host = os.environ.get('HOST', '127.0.0.1')

Handler = http.server.SimpleHTTPRequestHandler


class ThreadingTCPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
  allow_reuse_address = True
  daemon_threads = True

Handler.extensions_map={
  '.manifest': 'text/cache-manifest',
  '.html': 'text/html',
  '.png': 'image/png',
  '.jpg': 'image/jpg',
  '.svg': 'image/svg+xml',
  '.css': 'text/css',
  '.js':  'application/x-javascript',
  '.tsx': 'application/x-typescript',
  '.map': 'application/json',
  '': 'application/octet-stream', # Default
    }

httpd = ThreadingTCPServer((host, port), Handler)

print("serving at", host, "port", port)
httpd.serve_forever()

# command line version:
# python3 -m http.server $PORT
