#!/bin/bash
set -x #print commands
set -e #exit on failed command
set -u #fail on undefined variable

F=~/Dropbox/Code/leetcode/Solution.java

cat $F |sed '/^package .*/d'|sed '/^import .*/d' |sed 's/Solution extends Base/Solution/'|sed 's/^\([ ]*\)\(pr[(]\)/\1\/\/\2/'| tee >(pbcopy)
